class_name IState
extends Node

var canvas: Canvas


"""
Function called to handle initialisation logic for an IState node.
"""
func enter() -> void:
	pass

"""
Function called to handle destruction logic for an IState node.
"""
func exit() -> void:
	pass

"""
Function called for every background input event generated by the user. It
handles input events.

Parameters:
-----------
event: The background input event that was generated by the user. (InputEvent)

Returns:
--------
The next state. (Istate)
"""
func input(_event: InputEvent) -> IState:
	return null

"""
Function called every physics frame (every time the physics engine update). It
applies physics-based logic to a node.

Parameters:
-----------
delta: The time elapsed since the last physics frame, in seconds. (float)

Returns:
--------
The next state. (Istate)
"""
func physics_process(_delta: float) -> IState:
	return null

"""
Function called when a signal with arguments is received.

Parameters:
-----------
args: An array containing arguments. (Array)

Returns:
--------
The next state. (Istate)
"""
func parametrized_call(_args: Array) -> IState:
	return null

"""
Function called when a signal is received.

Parameters:
-----------
state: The state to switch to. (String)

Returns:
--------
The next state. (Istate)
"""
func switch_signal(_state: String) -> IState:
	return null

"""
Function called to switch to the previous state.
"""
func switch_to_previous_state() -> IState:
	return null

"""
Function called for every keyboard input event generated by the user. It
handles input events.

Parameters:
-----------
event: The keyboard input event that was generated by the user. (InputEvent)

Returns:
--------
The next state. (Istate)
"""
func keyboard_input(_event: InputEvent) -> IState:
	return null
