class_name IState
extends Node

var canvas: Canvas

"""
Function called to handle initialisation logic for an IState node.
"""
func enter() -> void:
	pass

"""
Function called to handle destruction logic for an IState node.
"""
func exit() -> void:
	pass

"""
Function called for every input event generated by the user or the system. It
handles input events.

Parameters:
-----------
event: The input event that was generated by the user or the system. (InputEvent)
"""
func input(event: InputEvent) -> IState:
	return null

"""
Function called every physics frame (every time the physics engine update). It
applies physics-based logic to a node.

Parameters:
-----------
delta: The time elapsed since the last physics frame, in seconds. (float)
"""
func physics_process(delta: float) -> IState:
	return null

func parametrized_call(args: Array) -> IState:
	return null

func switch_signal(state: String) -> IState:
	return null
	
func switch_to_previous_state() -> IState:
	return null

func keyboard_input(event: InputEvent) -> IState:
	return null
